### ISSUE TITLE
Issue: The app transforms white man into black when smiling parameter is reduced

### ISSUE THREAD

**Issue by tanmaylaud** [streamlit/demo-face-gan#13]
The webapp is transforming the face of a white man to a black man when the 'Smiling' is reduced to 0 . 

This can be considered Racist (where no smiling is being indicated a trait of a Black man) and should be fixed to avoid backlash in future. 

**To reproduce:**
- Select Young as 60
- Select Smiling as 90
- Select Male as 100
- Now drop Smiling to 0 .

**Comment by randyzwitch** [comment]
Hi @tanmaylaud, thanks for bringing this to our attention.

While this is an absolutely valid concern, and something the AI field in general needs to do a much better job of considering, it's important to realize that this demo is providing a front-end to _someone else's pre-trained model_. The details of this model are specifically highlighted as part of the [README](https://github.com/streamlit/demo-face-gan/blob/master/pg_gan/README.md) in the [model subfolder](https://github.com/streamlit/demo-face-gan/tree/master/pg_gan). 

In many ways, this demo could be considered a positive warning to future researchers. Streamlit makes it easy to quickly test the assumptions and parameter space of a model, which can help surface these sorts of issues _before_ a model is released.

It's beyond the scope of this demo to actually do state-of-the-art research, but should an external party have a more fair model that we can use as a demo, we'd be happy to incorporate that one as either an additional choice or replacement.

Best,
Randy
