### ISSUE TITLE
"open in streamlit" app is broken?

### ISSUE THREAD

**Issue by rabernat** [streamlit/demo-face-gan#17]
Thanks for providing this cool open-source tool to the community! 👏 

I wanted to try out streamlit without installing it locally so I clicked this badge:

[![Open in Streamlit](https://static.streamlit.io/badges/streamlit_badge_black_white.svg)](https://share.streamlit.io/streamlit/demo-face-gan/)

The app started up fine, but if I changed any of the sliders, I just got a missing image icon.

![image](https://user-images.githubusercontent.com/1197350/101269550-e6399c00-373d-11eb-9836-622ba4ccfa8a.png)

Not sure if I have done something wrong or if this is a bug...

**Comment by randyzwitch** [comment]
Thanks for reporting. Closing, as whatever problem might have existed is now resolved.
