### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by alessandroCiciarelli** [streamlit/demo-face-gan#27]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://share.streamlit.io/streamlit/demo-face-gan) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by arnaudmiribel** [comment]
Hi @alessandroCiciarelli, 

Thanks for the notification! The app is live again, so I'll close this.
