### ISSUE TITLE
lmdb should be installed using conda instead of pip

### ISSUE THREAD

**Issue by ucalyptus** [streamlit/demo-face-gan#5]
In the pip version , C++ compilation could lead/is leading to wheel build errors.
The conda precompiled package solved this hassle for lmdb.

**Comment by arraydude** [comment]
Hey @ucalyptus ,

Could you give us more details about your environment information ?
- Streamlit version: (get it with `$ streamlit version`)
- Python version: (get it with `$ python --version`)
- Using Conda? PipEnv? PyEnv? Pex?
- OS version:
- Browser version:

If you are in MacOS, do you have installed the latest "xcode-developer tools"?

**Comment by ucalyptus** [comment]
- Ubuntu 18.04.4 LTS Bionic Beaver
- pip 20.0.2
- Using Conda 4.8.3
- Python 3.6 inside the environment
- Google Chrome 80.0.3987.163 (Official Build) (64-bit)

@arraydude

**Comment by randyzwitch** [comment]
I just validated that the install is working correctly for Python 3.6 and 3.7 via pip, so going to close this for now. If this is still an issue @ucalyptus, please let me know and I'm happy to re-open.
