### ISSUE TITLE
TF already compatible with Python 3.7

### ISSUE THREAD

**Issue by apolmig** [streamlit/demo-face-gan#7]
Hi, just tried it and works with Python 3.7, so that should not be an issue anymore, that way you can reduce friction to try the demo.

Btw, great work and awesome Streamlit If you can deploy it even better to evangelize.

**Comment by randyzwitch** [comment]
Thanks for the note @apolmig, I also confirmed that here https://github.com/streamlit/demo-face-gan/issues/6#issuecomment-649760646

I'll make a change to our README to indicate that 3.7 also works.
